/*
 * Copyright (c) 2009 ... 2021 2022
 *     John McCue <jmccue@jmcunx.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/*
 * Generated by ~/src/j_utils/util/bin/mk_long_help.sh
 *           on Wed Nov 25 18:31:49 EST 2009
 */
#include <stdio.h>
#include <stdlib.h>

#include <j_lib2m.h>

int show_help_long(FILE *fp)
{

  fprintf(fp, "jbold(1)                                                              jbold(1)\n");
  fprintf(fp, "\n");
  fprintf(fp, "NAME\n");
  fprintf(fp, "       jbold - Bold text for printing on a dot matrix printer\n");
  fprintf(fp, "\n");
  fprintf(fp, "SYNOPSIS\n");
  fprintf(fp, "       jbold [OPTIONS] [FILE...]\n");
  fprintf(fp, "\n");
  fprintf(fp, "DESCRIPTION\n");
  fprintf(fp, "       Print  each  ASCII character as bold, this is useful when printing text\n");
  fprintf(fp, "       data on a dot matrix printer.  Can be used to bold output of  pr(1)  or\n");
  fprintf(fp, "       nroff(1).  Example:\n");
  fprintf(fp, "           pr -n jbold.c | jbold %cB 1 | lpr\n", SWITCH_CHAR);
  fprintf(fp, "\n");
  fprintf(fp, "       If  no  files  (FILE)  are specified on the command line or if FILE has\n");
  fprintf(fp, "       name \"-\", stdin (Standard Input) is used.\n");
  fprintf(fp, "\n");
  fprintf(fp, "OPTIONS\n");
  fprintf(fp, "       %cB num Optional, but if not specified there is no point  to  this  com-\n", SWITCH_CHAR);
  fprintf(fp, "              mand.   This specifies the number of overstrikes per ASCII char-\n");
  fprintf(fp, "              acter.  Range is 0 -- 10, 0 means no overstrikes, 10  means  ten\n");
  fprintf(fp, "              overstrikes.   The  higher the number the darker the text.  Zero\n");
  fprintf(fp, "              is the same as not specifying this argument.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       %ce file\n", SWITCH_CHAR);
  fprintf(fp, "              OPTIONAL - Errors written to the  file  specified,  defaults  to\n");
  fprintf(fp, "              stderr.  Note, not all errors will be written to the file speci-\n");
  fprintf(fp, "              fied, this depends upon where the error occur.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       %cf     Force file create.  Create file even if the target file exists.\n", SWITCH_CHAR);
  fprintf(fp, "\n");
  fprintf(fp, "       %ch     Show brief help and exit\n", SWITCH_CHAR);
  fprintf(fp, "\n");
  fprintf(fp, "       %co file\n", SWITCH_CHAR);
  fprintf(fp, "              OPTIONAL - Write output to the file specified, defaults to  std-\n");
  fprintf(fp, "              out.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       %cT num Expand  tabs  to  spaces,  if specified you would usually assign\n", SWITCH_CHAR);
  fprintf(fp, "              'num' to 8.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       %cV     Output version information and exit.\n", SWITCH_CHAR);
  fprintf(fp, "\n");
  fprintf(fp, "ENVIRONMENT\n");
  fprintf(fp, "       These variables can be set to change the default values  of  the  argu-\n");
  fprintf(fp, "       ments.   Command  line switches will override the values represented by\n");
  fprintf(fp, "       these variables:\n");
  fprintf(fp, "\n");
  fprintf(fp, "       JBOLD_BOLD\n");
  fprintf(fp, "              Overstrike this many times.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       JBOLD_ERR\n");
  fprintf(fp, "              Default stderr to write to the file specified in this variable.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       JBOLD_FORCE\n");
  fprintf(fp, "              Set to '0' to abort if the target file exists.  Set  to  '1'  to\n");
  fprintf(fp, "              always overwrite existing files.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       JBOLD_OUT\n");
  fprintf(fp, "              Default stdout to write to the file specified in this variable.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       JBOLD_TAB\n");
  fprintf(fp, "              Expand tabs to the numeric value specified in this variable.\n");
  fprintf(fp, "\n");
  fprintf(fp, "DIAGNOSTICS\n");
  fprintf(fp, "       If  environment  variables  \"JBOLD_OUT\"  and/or \"JBOLD_ERR\" is set, you\n");
  fprintf(fp, "       must unset the variables to use stdout/stderr.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       This is a simple text 'bold' utility.  As noted above, you use use this\n");
  fprintf(fp, "       to filter output of pr(1) or nroff(1).\n");
  fprintf(fp, "\n");
  fprintf(fp, "       jbold knows nothing about page size.\n");
  fprintf(fp, "\n");
  fprintf(fp, "       jbold assumes ASCII text, Unicode or UTF-8 not supported.\n");
  fprintf(fp, "\n");
  fprintf(fp, "ERROR-CODES\n");
  fprintf(fp, "       0 success\n");
  fprintf(fp, "       1 processing error or help/rev displayed\n");
  fprintf(fp, "\n");
  fprintf(fp, "SEE-ALSO\n");
  fprintf(fp, "       jexpand(1), nroff(1), pr(1), printdoc(1)\n");
  fprintf(fp, "\n");
  fprintf(fp, "                                                                      jbold(1)\n");

  return(EXIT_FAILURE);

} /* show_help_long() */
